name: minfin_splash
description: Minfin proyektlari uchun splash, sizga to'g'ri kelsa ishlatishingiz mumkin
version: 0.0.2
homepage: https://github.com/abbos2101/minfin_splash

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0